name: Build Push Sign
on: { push: { branches: ['main'] } }

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v1

      - name: Login to GitHub
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: sigstore/cosign-installer@main

      - name: Sign the images
        run: |
          cosign sign -y \
            ghcr.io/khaledemaradev/policies/verify-images@sha256:4de4f79285ed6836ac57f839623fc68522797cf4526c944202a772e39067d34f
        env:
          COSIGN_EXPERIMENTAL: 1

      - name: Verify the pushed tags
        run: cosign verify ghcr.io/khaledemaradev/policies/verify-images@sha256:4de4f79285ed6836ac57f839623fc68522797cf4526c944202a772e39067d34f
        env:
          COSIGN_EXPERIMENTAL: 1